version: '3.7'
services:
    pg:
      image: postgres:11
      environment:
          - POSTGRES_USER
          - POSTGRES_PASSWORD
          - POSTGRES_DB
      ports:
          - "${PG_HOSTS_PORT}:5432"
      volumes:
        - db-data:/var/lib/postgresql/data
        - ./database/createtables.sql:/docker-entrypoint-initdb.d/1-createtables.sql
        - ./database/populatedb.sql:/docker-entrypoint-initdb.d/2-populatedb.sql
      deploy:
        resources:
          limits:
            cpus: '0.50'
            memory: 1G
          reservations:
            cpus: '0.25'
            memory: 100M


    api:
      build: .
      image: kraken-api:latest
      environment:
          - POSTGRES_USER
          - POSTGRES_PASSWORD
      ports:
          - "${API_HOSTS_PORT}:8080"
      deploy:
        resources:
          limits:
            cpus: '0.50'
            memory: 1G
          reservations:
            cpus: '0.25'
            memory: 100M

    front:
      build: front
      image: front:latest
      ports:
          - "${FRONT_HOSTS_PORT}:80"
      deploy:
        resources:
          limits:
            cpus: '0.50'
            memory: 1G
          reservations:
            cpus: '0.25'
            memory: 100M

volumes:
  db-data: